# Hurricane Analysis

### Overview
This project is slightly different than others you have encountered thus far on Codecademy. Instead of a step-by-step tutorial, this project contains a series of open-ended requirements which describe the project you’ll be building. There are many possible ways to correctly fulfill all of these requirements, and you should expect to use the internet, Codecademy, and other resources when you encounter a problem that you cannot easily solve.

### Project Goals
You will work to write several functions that organize and manipulate data about Category 5 Hurricanes, the strongest hurricanes as rated by their wind speed. Each one of these functions will use a number of parameters, conditionals, lists, dictionaries, string manipulation, and return statements.

### Setup Instructions
You have two options of completing this assignment. Either here, within Codecademy’s output terminal, or on your own, in case you’re more comfortable using a Jupyter notebook.If you choose to do this project on your computer instead of Codecademy, you can download what you’ll need by clicking the “Download” button below. If you need help setting up your computer, be sure to check out our setup guides:
- Command Line Interface Setup
- Introducing Jupyter Notebook
- Setting up Jupyter Notebook
- Getting Started with Jupyter
- Getting More out of Jupyter Notebook

Open Hurricane Analysis.ipynb and follow the steps in the Jupyter Notebook. If you get stuck, you can look at Hurricane Analysis_Solution.ipynb for the answer.



## Prerequisites
In order to complete this project, you should have completed the Loops and Dictionaries sections of the Learn Python 3 Course. This content is also covered in the Data Scientist Career Path.

## Project Requirements
Hurricanes, also known as cyclones or typhoons, are one of the most powerful forces of nature on Earth. Due to climate change caused by human activity, the number and intensity of hurricanes has risen, calling for better preparation by the many communities that are devastated by them. As a concerned environmentalist, you want to look at data about the most powerful hurricanes that have occurred.

Begin by looking at the `damages` list. The list contains strings representing the total cost in USD(`$`) caused by `34` category 5 hurricanes (wind speeds ≥ 157 mph (252 km/h )) in the Atlantic region. For some of the hurricanes, damage data was not recorded (`"Damages not recorded"`), while the rest are written in the format `"Prefix-B/M"`, where B stands for billions (`1000000000`) and M stands for millions (`1000000`).

Write a function that returns a new list of updated damages where the recorded data is converted to float values and the missing data is retained as `"Damages not recorded"`.

Test your function with the data stored in `damages`.

In [1]:
# names of hurricanes
names = ['Cuba I', 'San Felipe II Okeechobee', 'Bahamas', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Labor Day', 'New England', 'Carol', 'Janet', 'Carla', 'Hattie', 'Beulah', 'Camille', 'Edith', 'Anita', 'David', 'Allen', 'Gilbert', 'Hugo', 'Andrew', 'Mitch', 'Isabel', 'Ivan', 'Emily', 'Katrina', 'Rita', 'Wilma', 'Dean', 'Felix', 'Matthew', 'Irma', 'Maria', 'Michael']

# months of hurricanes
months = ['October', 'September', 'September', 'November', 'August', 'September', 'September', 'September', 'September', 'September', 'September', 'October', 'September', 'August', 'September', 'September', 'August', 'August', 'September', 'September', 'August', 'October', 'September', 'September', 'July', 'August', 'September', 'October', 'August', 'September', 'October', 'September', 'September', 'October']

# years of hurricanes
years = [1924, 1928, 1932, 1932, 1933, 1933, 1935, 1938, 1953, 1955, 1961, 1961, 1967, 1969, 1971, 1977, 1979, 1980, 1988, 1989, 1992, 1998, 2003, 2004, 2005, 2005, 2005, 2005, 2007, 2007, 2016, 2017, 2017, 2018]

# maximum sustained winds (mph) of hurricanes
max_sustained_winds = [165, 160, 160, 175, 160, 160, 185, 160, 160, 175, 175, 160, 160, 175, 160, 175, 175, 190, 185, 160, 175, 180, 165, 165, 160, 175, 180, 185, 175, 175, 165, 180, 175, 160]

# areas affected by each hurricane
areas_affected = [['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], ['The Bahamas', 'Northeastern United States'], ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], ['The Bahamas', 'Cuba', 'Florida', 'Texas', 'Tamaulipas'], ['Jamaica', 'Yucatn Peninsula'], ['The Bahamas', 'Florida', 'Georgia', 'The Carolinas', 'Virginia'], ['Southeastern United States', 'Northeastern United States', 'Southwestern Quebec'], ['Bermuda', 'New England', 'Atlantic Canada'], ['Lesser Antilles', 'Central America'], ['Texas', 'Louisiana', 'Midwestern United States'], ['Central America'], ['The Caribbean', 'Mexico', 'Texas'], ['Cuba', 'United States Gulf Coast'], ['The Caribbean', 'Central America', 'Mexico', 'United States Gulf Coast'], ['Mexico'], ['The Caribbean', 'United States East coast'], ['The Caribbean', 'Yucatn Peninsula', 'Mexico', 'South Texas'], ['Jamaica', 'Venezuela', 'Central America', 'Hispaniola', 'Mexico'], ['The Caribbean', 'United States East Coast'], ['The Bahamas', 'Florida', 'United States Gulf Coast'], ['Central America', 'Yucatn Peninsula', 'South Florida'], ['Greater Antilles', 'Bahamas', 'Eastern United States', 'Ontario'], ['The Caribbean', 'Venezuela', 'United States Gulf Coast'], ['Windward Islands', 'Jamaica', 'Mexico', 'Texas'], ['Bahamas', 'United States Gulf Coast'], ['Cuba', 'United States Gulf Coast'], ['Greater Antilles', 'Central America', 'Florida'], ['The Caribbean', 'Central America'], ['Nicaragua', 'Honduras'], ['Antilles', 'Venezuela', 'Colombia', 'United States East Coast', 'Atlantic Canada'], ['Cape Verde', 'The Caribbean', 'British Virgin Islands', 'U.S. Virgin Islands', 'Cuba', 'Florida'], ['Lesser Antilles', 'Virgin Islands', 'Puerto Rico', 'Dominican Republic', 'Turks and Caicos Islands'], ['Central America', 'United States Gulf Coast (especially Florida Panhandle)']]

# damages (USD($)) of hurricanes
damages = ['Damages not recorded', '100M', 'Damages not recorded', '40M', '27.9M', '5M', 'Damages not recorded', '306M', '2M', '65.8M', '326M', '60.3M', '208M', '1.42B', '25.4M', 'Damages not recorded', '1.54B', '1.24B', '7.1B', '10B', '26.5B', '6.2B', '5.37B', '23.3B', '1.01B', '125B', '12B', '29.4B', '1.76B', '720M', '15.1B', '64.8B', '91.6B', '25.1B']

# deaths for each hurricane
deaths = [90,4000,16,3103,179,184,408,682,5,1023,43,319,688,259,37,11,2068,269,318,107,65,19325,51,124,17,1836,125,87,45,133,603,138,3057,74]


In [2]:
# Update Recorded Damages
def convert_damages_record(damages):
    conversion = {"M": 1000000, "B": 1000000000}
    update_damages = []
    
    for damage in damages:
        if damage == "Damages not recorded":
            update_damages.append(damage)
        elif damage.find("M") != -1:
            update_damages.append(float(damage[0:damage.find("M")]) * conversion["M"])
        elif damage.find("B") != -1:
            update_damages.append(float(damage[0:damage.find("B")]) * conversion["B"])
            
    return update_damages

# test function by updating damages
damages = convert_damages_record(damages)
print(damages)

['Damages not recorded', 100000000.0, 'Damages not recorded', 40000000.0, 27900000.0, 5000000.0, 'Damages not recorded', 306000000.0, 2000000.0, 65800000.0, 326000000.0, 60300000.0, 208000000.0, 1420000000.0, 25400000.0, 'Damages not recorded', 1540000000.0, 1240000000.0, 7100000000.0, 10000000000.0, 26500000000.0, 6200000000.0, 5370000000.0, 23300000000.0, 1010000000.0, 125000000000.0, 12000000000.0, 29400000000.0, 1760000000.0, 720000000.0, 15100000000.0, 64800000000.0, 91600000000.0, 25100000000.0]


Additional data collected on the `34` strongest Atlantic hurricanes are provided in a series of lists. The data includes:
- names: names of the hurricanes
- months: months in which the hurricanes occurred
- years: years in which the hurricanes occurred
- max_sustained_winds: maximum sustained winds (miles per hour) of the hurricanes
- areas_affected: list of different areas affected by each of the hurricanes
- deaths: total number of deaths caused by each of the hurricanes

The data is organized such that the data at each index, from `0` to `33`, corresponds to the same hurricane.

For example, names`[0]` yields the “Cuba I” hurricane, which ouccred in `months[0]` (October) `years[0]` (1924).

Write a function that constructs a dictionary made out of the lists, where the keys of the dictionary are the names of the hurricanes, and the values are dictionaries themselves containing a key for each piece of data (`Name`, `Month`, `Year`,`Max Sustained Wind`, `Areas Affected`, `Damage`, `Death`) about the hurricane.

Thus the key `"Cuba I"` would have the value: `{'Name': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Deaths': 90}`.

Test your function on the lists of data provided.

In [3]:
# Create a Table
def create_hurricanes_table(names, months, years, max_sustained_winds, areas_affected, damages, deaths):
    hurricanes_dicts = {}
    
    for i in range(0, len(names)):
        hurricanes_dicts[names[i]] = {
            "Names" : names[i],
            "Month" : months[i],
            "Year" : years[i],
            "Max Sustained Wind" : max_sustained_winds[i],
            "Areas Affected" : areas_affected[i],
            "Damage" : damages[i],
            "Death" : deaths[i]
        }
    return hurricanes_dicts

# Create and view the hurricanes dictionary
hurricanes = create_hurricanes_table(names, months, years, max_sustained_winds, areas_affected, damages, deaths)
print(hurricanes["Cuba I"])

{'Names': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Death': 90}


In [4]:
print(hurricanes)

{'Cuba I': {'Names': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Death': 90}, 'San Felipe II Okeechobee': {'Names': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Death': 4000}, 'Bahamas': {'Names': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Death': 16}, 'Cuba II': {'Names': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Death': 3103}, 'CubaBrownsville': {'Names': 'CubaBrownsville', 'Month': 'August',

In addition to organizing the hurricanes in a dictionary with names as the key, you want to be able to organize the hurricanes by year.

Write a function that converts the current dictionary of hurricanes to a new dictionary, where the keys are years and the values are lists containing a dictionary for each hurricane that occurred in that year.

For example, the key 1932 would yield the value: `[{'Name': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Deaths': 16}, {'Name': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Deaths': 3103}]`.

Test your function on your hurricane dictionary.

In [5]:
# Organizing by Year
def hurricanes_organized_by_year(hurricanes):
    hurricanes_by_years = {}
    
    for i in hurricanes.values():
        current_year = i["Year"]
        
        if current_year in hurricanes_by_years:
            hurricanes_by_years[current_year].append(i)
        else:
            hurricanes_by_years[current_year] = [i]
            
    return hurricanes_by_years

# create a new dictionary of hurricanes with year and key
hurricanes_by_years = hurricanes_organized_by_year(hurricanes)
print(hurricanes_by_years)

{1924: [{'Names': 'Cuba I', 'Month': 'October', 'Year': 1924, 'Max Sustained Wind': 165, 'Areas Affected': ['Central America', 'Mexico', 'Cuba', 'Florida', 'The Bahamas'], 'Damage': 'Damages not recorded', 'Death': 90}], 1928: [{'Names': 'San Felipe II Okeechobee', 'Month': 'September', 'Year': 1928, 'Max Sustained Wind': 160, 'Areas Affected': ['Lesser Antilles', 'The Bahamas', 'United States East Coast', 'Atlantic Canada'], 'Damage': 100000000.0, 'Death': 4000}], 1932: [{'Names': 'Bahamas', 'Month': 'September', 'Year': 1932, 'Max Sustained Wind': 160, 'Areas Affected': ['The Bahamas', 'Northeastern United States'], 'Damage': 'Damages not recorded', 'Death': 16}, {'Names': 'Cuba II', 'Month': 'November', 'Year': 1932, 'Max Sustained Wind': 175, 'Areas Affected': ['Lesser Antilles', 'Jamaica', 'Cayman Islands', 'Cuba', 'The Bahamas', 'Bermuda'], 'Damage': 40000000.0, 'Death': 3103}], 1933: [{'Names': 'CubaBrownsville', 'Month': 'August', 'Year': 1933, 'Max Sustained Wind': 160, 'Areas

You believe that knowing how often each of the areas of the Atlantic are affected by these strong hurricanes is important for making preparations for future hurricanes.

Write a function that counts how often each area is listed as an affected area of a hurricane. Store and return the results in a dictionary where the keys are the affected areas and the values are counts of how many times the areas were affected.

Test your function on your hurricane dictionary.

In [6]:
# Counting Damaged Areas
def count_damaged_areas(hurricanes):
    count_area = {}
    
    for area in hurricanes.values():
        areas = area["Areas Affected"]
        
        for i in range(0, len(areas)):
            if areas[i] in count_area:
                count_area[areas[i]] += 1
            else:
                count_area[areas[i]] = 1
    return count_area

# create dictionary of areas to store the number of hurricanes involved in
affected_areas_count = count_damaged_areas(hurricanes)
print(affected_areas_count)

{'Central America': 9, 'Mexico': 7, 'Cuba': 6, 'Florida': 6, 'The Bahamas': 7, 'Lesser Antilles': 4, 'United States East Coast': 3, 'Atlantic Canada': 3, 'Northeastern United States': 2, 'Jamaica': 4, 'Cayman Islands': 1, 'Bermuda': 2, 'Texas': 4, 'Tamaulipas': 1, 'Yucatn Peninsula': 3, 'Georgia': 1, 'The Carolinas': 1, 'Virginia': 1, 'Southeastern United States': 1, 'Southwestern Quebec': 1, 'New England': 1, 'Louisiana': 1, 'Midwestern United States': 1, 'The Caribbean': 8, 'United States Gulf Coast': 6, 'United States East coast': 1, 'South Texas': 1, 'Venezuela': 3, 'Hispaniola': 1, 'South Florida': 1, 'Greater Antilles': 2, 'Bahamas': 2, 'Eastern United States': 1, 'Ontario': 1, 'Windward Islands': 1, 'Nicaragua': 1, 'Honduras': 1, 'Antilles': 1, 'Colombia': 1, 'Cape Verde': 1, 'British Virgin Islands': 1, 'U.S. Virgin Islands': 1, 'Virgin Islands': 1, 'Puerto Rico': 1, 'Dominican Republic': 1, 'Turks and Caicos Islands': 1, 'United States Gulf Coast (especially Florida Panhandle)

Write a function that finds the area affected by the most hurricanes, and how often it was hit.

Test your function on your affected area dictionary.

In [7]:
# Calculating Maximum Hurricane Count
def calculate_max_hurricanes_count(affected_areas_count):
    max_area = " "
    max_area_count = 0
    
    for max in affected_areas_count:
        if affected_areas_count[max] > max_area_count:
            max_area_count = affected_areas_count[max]
        else:
            max_area = max
    
    return max_area, max_area_count
            

# find most frequently affected area and the number of hurricanes involved in
calculate_max_hurricanes_count(affected_areas_count)

('United States Gulf Coast (especially Florida Panhandle)', 9)

Write a function that finds the hurricane that caused the greatest number of deaths, and how many deaths it caused.

Test your function on your hurricane dictionary.

In [8]:
# Calculating the Deadliest Hurricane
def calculate_deadly_hurricanes(hurricanes):
    max_mortality_cane = ""
    max_mortality = 0
    
    for death in hurricanes:
        if hurricanes[death]["Death"] > max_mortality:
            max_mortality = hurricanes[death]["Death"]
        else:
            max_mortality_cane = death
    return max_mortality_cane, max_mortality

# find highest mortality hurricane and the number of deaths
calculate_deadly_hurricanes(hurricanes)

('Michael', 19325)

Just as hurricanes are rated by their windspeed, you want to try rating hurricanes based on other metrics.

Write a function that rates hurricanes on a mortality scale according to the following ratings, where the key is the rating and the value is the upper bound of deaths for that rating.

mortality_scale = {0: 0,
                   1: 100,
                   2: 500,
                   3: 1000,
                   4: 10000}
                   
For example, a hurricane with a 1 mortality rating would have resulted in greater than 0 but less than or equal to 100 deaths. A hurricane with a 5 mortality rating would have resulted in greater than 10000 deaths.

Store the hurricanes in a new dictionary where the keys are mortality ratings and the values are lists containing a dictionary for each hurricane that falls into that mortality rating.

Test your function on your hurricane dictionary.

In [9]:
# Rating Hurricanes by Mortality
def rating_hurricanes_mortality(hurricanes):
    hurricanes_by_mortality = {0:[], 1:[], 2:[], 3:[], 4:[], 5:[]}
    mortality_scales = {0: 0, 1: 100, 2: 500, 3: 1000, 4: 10000}
    
    for mortality in hurricanes:
        death = hurricanes[mortality]["Death"]
        
        if death > mortality_scales[4]:
            hurricanes_by_mortality[5].append(mortality)
        elif death > mortality_scales[3]:
             hurricanes_by_mortality[4].append(mortality)
        elif death > mortality_scales[2]:
             hurricanes_by_mortality[3].append(mortality)
        elif death > mortality_scales[1]:
             hurricanes_by_mortality[2].append(mortality)
        elif death > mortality_scales[0]:
             hurricanes_by_mortality[1].append(mortality)
        else:
             hurricanes_by_mortality[0].append(mortality)
     
    return hurricanes_by_mortality

# categorize hurricanes in new dictionary with mortality severity as key
print(rating_hurricanes_mortality(hurricanes))

{0: [], 1: ['Cuba I', 'Bahamas', 'Carol', 'Carla', 'Edith', 'Anita', 'Andrew', 'Isabel', 'Emily', 'Wilma', 'Dean', 'Michael'], 2: ['CubaBrownsville', 'Tampico', 'Labor Day', 'Hattie', 'Camille', 'Allen', 'Gilbert', 'Hugo', 'Ivan', 'Rita', 'Felix', 'Irma'], 3: ['New England', 'Beulah', 'Matthew'], 4: ['San Felipe II Okeechobee', 'Cuba II', 'Janet', 'David', 'Katrina', 'Maria'], 5: ['Mitch']}


Write a function that finds the hurricane that caused the greatest damage, and how costly it was.

Test your function on your hurricane dictionary.

In [10]:
# write your greatest damage function here:
def max_hurricanes_damage(hurricanes):
    max_damage_cane = ''
    max_damage = 0
    
    for damage in hurricanes:
        if hurricanes[damage]["Damage"] == "Damages not recorded":
            continue
        elif hurricanes[damage]["Damage"] > max_damage:
            max_damage = hurricanes[damage]["Damage"]
            max_damage_cane = damage
            
    return max_damage_cane, max_damage

print(max_hurricanes_damage(hurricanes))

('Katrina', 125000000000.0)


Lastly, you want to rate hurricanes according to how much damage they cause.

Write a function that rates hurricanes on a damage scale according to the following ratings, where the key is the rating and the value is the upper bound of damage for that rating.

damage_scale = {0: 0,
                1: 100000000,
                2: 1000000000,
                3: 10000000000,
                4: 50000000000}
                
For example, a hurricane with a 1 damage rating would have resulted in damages greater than 0 USD but less than or equal to 100000000 USD. A hurricane with a 5 damage rating would have resulted in damages greater than 50000000000 USD (talk about a lot of money).

Store the hurricanes in a new dictionary where the keys are damage ratings and the values are lists containing a dictionary for each hurricane that falls into that damage rating.

Test your function on your hurricane dictionary.

In [13]:
# write your catgeorize by damage function here:
def rating_hurricanes_by_damage(hurricanes):
    damage_scale ={0: 0, 1: 100000000, 2: 1000000000, 3: 10000000000, 4: 50000000000}
    hurricanes_by_damage = {0:[], 1:[], 2:[], 3:[], 4:[], 5:[]}
    
    for damage in hurricanes:
        damages = hurricanes[damage]["Damage"]
        
        if damages == "Damages not recorded":
            continue
        elif damages > damage_scale[4]:
            hurricanes_by_damage[5].append(damage)
        elif damages > damage_scale[3]:
            hurricanes_by_damage[4].append(damage)
        elif damages > damage_scale[2]:
            hurricanes_by_damage[3].append(damage)
        elif damages > damage_scale[1]:
            hurricanes_by_damage[2].append(damage)
        elif damages > damage_scale[0]:
            hurricanes_by_damage[1].append(damage)
        else:
            hurricanes_by_damage[0].append(damage)
            
    return hurricanes_by_damage

print(rating_hurricanes_by_damage(hurricanes))

{0: [], 1: ['San Felipe II Okeechobee', 'Cuba II', 'CubaBrownsville', 'Tampico', 'Carol', 'Janet', 'Hattie', 'Edith'], 2: ['New England', 'Carla', 'Beulah', 'Felix'], 3: ['Camille', 'David', 'Allen', 'Gilbert', 'Hugo', 'Mitch', 'Isabel', 'Emily', 'Dean'], 4: ['Andrew', 'Ivan', 'Rita', 'Wilma', 'Matthew', 'Michael'], 5: ['Katrina', 'Irma', 'Maria']}
